//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model1._6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int id { get; set; }
        public int Value { get; set; }
        public string Data { get; set; }
    }
}
